- Sharpmake.Generators/VisualStudio/ProjectOptionsGenerator.cs
- Sharpmake/Project.Configuration.cs
* Setting LinkerPdbFilePath to null or an empty string will make Visual Studio use the default.
* Setting CompilerPdbFilePath to null or an empty string will make Visual Studio use the default.
> Added default option for PDB.

- Sharpmake.Application/CommandLineArguments.cs
- Sharpmake/DebugProjectGenerator.cs
- Sharpmake/Exception.cs
Properly implemented exceptions according to the guildelines. (See https://blog.gurock.com/articles/creating-custom-exceptions-in-dotnet/)
* All Sharpmake exceptions are now [Serializable].
* All Sharpmake exceptions now have the protected constructor needed for deserialization.
This changelist does *not* put the `Exception` suffix to the Sharpmake exception classes that do not, in case it breaks existing scripts. (Although scripts should not catch Error or InternalError exceptions.)
Tip: Use the built-in code snippet in VS to declare a custom exception class.
> Fixed exceptions classes.

- Sharpmake.Generators/FastBuild/Bff.Template.cs
- Sharpmake.Generators/VisualStudio/ProjectOptionsGenerator.cs
- Sharpmake.Platforms/Sharpmake.CommonPlatforms/BasePlatform.Vcxproj.Template.cs
- Sharpmake/Options.Vc.cs
Adds `CPP17, GNU17, Latest` to the `Options.Vc.Compiler.CppLanguageStandard` option and implements it for VS projects. C++98/11 are ignored as MSVC only provides options for C++14/17 and the working draft. The GNU C++ options are interpreted as the corresponding standard C++ options.
It might make sense to create a separate on/off option for the GNU extensions and get rid of the `GNU*` options in `CppLanguageStandard`.
> C++ standard level support for VS

- Sharpmake.Generators/VisualStudio/ProjectOptionsGenerator.cs
- Sharpmake/Options.Vc.cs
Hi,
LLVM 6.0 adds newer platform options to Visual Studio, so I added them to Sharpmake.
Cheers,
Marcin
> Added newer versions of LLVM toolchain

- Sharpmake/Assembler.cs
If compilation fails with an error such as this:
`testproj.sharpmake.cs(59,2) : error CS1513: } expected`
Shaprmake throws System.FormatException because the error format string contains a character which is considered as a special formatting character. This can be very confusing and prevents users to find the actual problem which is in their script code.
> Fix a System.FormatException caused by invalid format string

- Sharpmake.UnitTests/JsonSerializerTest.cs
- Sharpmake/Util.cs
JSON float serialization currently can be affected by the default system CultureInfo.
Changed JSON serialization to use CultureInvariant when writing float types, added test.
> Make sure JSON float serialization is culture invariant

- .appveyor.yml
- CompileSharpmake.sh
- bootstrap.bat
- bootstrap.sh
Add equivalent of CompileSharpmake.bat in Bash for MacOS and adapt bootstrap.sh to call it.
Tested on MacOS 10.15.4
> Compile script macos

- samples/Sharpmake.Samples.sharpmake.cs
With this you can hit f5 on a sample library again.
> [Samples] Fix launch arguments to work with new sharpmake output location

- Sharpmake.Generators/FastBuild/Bff.Template.cs
- Sharpmake.Generators/FastBuild/Bff.Util.cs
- Sharpmake/Project.Configuration.cs
FastBuild's **Exec** step has ._ExecAlways_ parameter that was not exposed to the developers that use SharpMake. 
Its valuable for code generation tasks that should be run every time.
More details here:
https://www.fastbuild.org/docs/functions/exec.html
> .ExecAlways flag added to BuildStepExecutable step (Exec)

- Sharpmake.Generators/FastBuild/Bff.Template.cs
- Sharpmake.Generators/FastBuild/Bff.cs
- Sharpmake.Generators/VisualStudio/ProjectOptionsGenerator.cs
- Sharpmake.Platforms/Sharpmake.CommonPlatforms/BasePlatform.Vcxproj.Template.cs
- Sharpmake/Options.Vc.cs
Visual Studio 2019 version 16.8.0 introduced /std:c11 and /std:c17 switches to set the C language standard. The 'Legacy' standard is used by default.
> Add support for Visual Studio 2019 /std:c11 and /std:c17 switches

- Sharpmake.Generators/VisualStudio/Csproj.cs
- Sharpmake/Project.cs
- samples/NetCore/DotNetCoreFrameworkHelloWorld/HelloWorld.sharpmake.cs
When creating netCore solution that uses launchSettings.json, if the project property `EnableDefaultItems` is false when the project start it won't use the the LaunchSettings.
I created a new project property called `EnableDefaultItems` (default value is false as before) in which allow to pass true and use EnableDefaultItems as true in the project and then we can use launchSettings.json when start the project.
> Add project EnableDefaultItems property

- Sharpmake/DebugProjectGenerator.cs
The fixed format is:
/sources(@'d:\folder\file1.sharpmake.cs',@'d:\anotherfolder\anotherfile.sharpmake.cs')
Previously the command line parameters were created in this format:
/sources(@'d:\folder\file1.sharpmake.cs;d:\anotherfolder\anotherfile.sharpmake.cs')
which results in the following exception when running the generated project:
The given path's format is not supported.
Stack trace:
Root stack trace:
at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
at System.IO.Path.GetFullPath(String path)
at Sharpmake.Application.Program.Argument.ValidateFiles(String[] files) in …
> Fixing invalid /sources command line parameters in the csproj.user file created via /generateDebugSolution

- Sharpmake/Project.cs
- samples/HelloXCode/HelloXCode.CommonProject.sharpmake.cs
- samples/HelloXCode/HelloXCode.Main.sharpmake.cs
- samples/HelloXCode/codebase/dll1/util_dll.cpp
- samples/HelloXCode/codebase/exe/main.cpp
- samples/HelloXCode/codebase/static lib2/util_static_lib2.cpp
- samples/HelloXCode/codebase/static_lib1/src/util_static_lib1.cpp
- samples/HelloXCode/external/external.cpp
- samples/HelloXCode/external/external.h
The AdditionalSourceRootPaths member never had the paths it contained resolved, resulting in paths that had mixed folder separators to not be looked up correctly inside of ResolveSourceFiles.
Ex: A path added to AdditionalSourcerootPaths on Mac OSX set as:
@"[project.SharpmakeCsPath]\..\externals\SomeExternal"
that expanded to:
/Users/SomeUser/Documents/SomeProject/sharpmake\\..\\externals\\SomeExternal
would fail to have the files in the directory looked up. Calling ResolvePath on the member causes the path to be normalized to:
/Users/SomeUser/Documents/SomeProject/externals/SomeExternal
> Resolve AdditionalSourceRootPaths before use

- .github/workflows/actions.yml
- Sharpmake.Generators/FastBuild/Bff.Util.cs
- Sharpmake.Generators/FastBuild/Bff.cs
- samples/CustomBuildStep/CustomBuildStep.sharpmake.cs
- samples/CustomBuildStep/Properties/AssemblyInfo.cs
- samples/CustomBuildStep/codebase/filegeneration.bat
- samples/Sharpmake.Samples.sharpmake.cs
- Adding missing variables to the "Declare"
- Fix multiple "Exec" with same output by adding it only once. Added validations to make sure each one has the exact same settings
- Adding a new sample that test CustomBuildStep. At build (from FastBuild or from MSBuild), the filegeneration.bat should be called before building the project. It is generating the "main.cpp".
> Fixing custom build step generation for FastBuild

- .github/workflows/actions.yml
- Sharpmake.Generators/FastBuild/MasterBff.cs
- samples/HelloEvents/HelloEvents.CommonProject.sharpmake.cs
- samples/HelloEvents/HelloEvents.CommonSolution.sharpmake.cs
- samples/HelloEvents/HelloEvents.CommonTarget.sharpmake.cs
- samples/HelloEvents/HelloEvents.Main.sharpmake.cs
- samples/HelloEvents/Properties/AssemblyInfo.cs
- samples/HelloEvents/codebase/HelloEvents.sharpmake.cs
- samples/HelloEvents/codebase/dll1/dll1.sharpmake.cs
- samples/HelloEvents/codebase/dll1/precomp.cpp
- samples/HelloEvents/codebase/dll1/precomp.h
- samples/HelloEvents/codebase/dll1/util_dll.cpp
- samples/HelloEvents/codebase/dll1/util_dll.h
- samples/HelloEvents/codebase/exe/exe.sharpmake.cs
- samples/HelloEvents/codebase/exe/main.cpp
- samples/HelloEvents/codebase/exe/stdafx.cpp
- samples/HelloEvents/codebase/exe/stdafx.h
- samples/HelloEvents/codebase/static lib2/static_lib2.sharpmake.cs
- samples/HelloEvents/codebase/static lib2/sub folder/useless_static_lib2.cpp
- samples/HelloEvents/codebase/static lib2/sub folder/useless_static_lib2.h
- samples/HelloEvents/codebase/static lib2/util_static_lib2.cpp
- samples/HelloEvents/codebase/static lib2/util_static_lib2.h
- samples/HelloEvents/codebase/static_lib1/src/ensure_debug.cpp
- samples/HelloEvents/codebase/static_lib1/src/ensure_release.cpp
- samples/HelloEvents/codebase/static_lib1/src/pch.cpp
- samples/HelloEvents/codebase/static_lib1/src/pch.h
- samples/HelloEvents/codebase/static_lib1/src/util_static_lib1.cpp
- samples/HelloEvents/codebase/static_lib1/src/util_static_lib1.h
- samples/HelloEvents/codebase/static_lib1/static_lib1.sharpmake.cs
- samples/Sharpmake.Samples.sharpmake.cs
Try and figure out if the source of the postbuild copies is an output of one of the targets, and if so move the Copy node declaration after the node that defines it, and add it as a PreBuildDependency
- Add a new sample to test those kind of events, registered to github actions
> [MasterBff] Fix target copy files of dependencies

- samples/FastBuildSimpleExecutable/FastBuildSimpleExecutable.sharpmake.cs
Missing this option causes cl.exe to fail when compiling multiple files at the same time.
Altough it's not needed for this simple file example, it serves as a guide for custom projects.
Personally, this would save me about 15 mins of researching :)
> Add /FS option to FastBuild example.

- Sharpmake.Platforms/Sharpmake.CommonPlatforms/BasePlatform.Vcxproj.Template.cs
- Sharpmake.Platforms/Sharpmake.CommonPlatforms/Linux/LinuxPlatform.Vcxproj.Template.cs
- Sharpmake/Project.Configuration.cs
In my project I hot reload DLL plugins, and for this reason I want to attach my debugger to a running executable instead of launching it.
The regression tests succeeded, I don't know if I have to provide anything else.
Thank you!
> Add support for VcxprojUserFile.LocalDebuggerAttach

- Sharpmake.UnitTests/PackageReferencesTest.cs
- Sharpmake/PackageReferences.cs
'ContentFile' => 'ContentFiles'
The enum value is used to serialize while serializing the project template, but the spelling of the enumeration is defined as 'contentFiles' here: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
Also: are there any plans for support of **IncludeAssets** and **ExcludeAssets**? 
And, what about the newer **buildMultitargeting** and **buildTransitive** enum values?
Best,
Fabian
> fix typo in PackageReferences.AssetsDependency 'ContentFile'

- Sharpmake.Generators/VisualStudio/Vcxproj.Template.cs
- Sharpmake.Generators/VisualStudio/Vcxproj.cs
- Sharpmake.Platforms/Sharpmake.CommonPlatforms/BasePlatform.Vcxproj.Template.cs
Added proper support for .Net Core (and .Net 5.0) C++/CLI-projects as per instructions here
https://docs.microsoft.com/en-us/dotnet/core/porting/cpp-cli (works for .Net 5.0) as well.
Note that CompileAsManaged-element had to be removed when compiling for .Net Core (or .Net 5.0) otherwise things fail due to Internal Compiler error.
> Added proper support for .Net Core/.Net 5.0 C++/CLI project support

- Sharpmake.Generators/VisualStudio/Csproj.Template.cs
- Sharpmake.Generators/VisualStudio/Csproj.cs
- Sharpmake/Project.cs
See https://docs.microsoft.com/en-us/aspnet/core/grpc/dotnet-grpc?view=aspnetcore-5.0
> Added support for Protobuf-includes in C# projects

- Sharpmake.Generators/VisualStudio/Csproj.Template.cs
- Sharpmake.Generators/VisualStudio/Csproj.cs
- Sharpmake/Options.CSharp.cs
Add support for the 'nullable' property in C# projects
See https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/nullable-reference-types
> Add support for the 'nullable' property in C# projects

- Sharpmake.Generators/VisualStudio/ProjectOptionsGenerator.cs
This patch adds a missing CPP20 option to the list of converted settings.
Without it, whenever a project uses specifically CPP20 standard,
it is not properly translated into NMake project, therefore
Intellisense (and similar software) doesn't pick it up correctly.
> Add missing CppLanguageStandard.CPP20 for NMake Intellisense helper.

- Sharpmake.Generators/VisualStudio/Vcxproj.cs
It fixes a bug when path for a custom command contain spaces.
Fixes #214
> Wrap custom command in quotes when using MSBuild

- Sharpmake.Generators/VisualStudio/ProjectOptionsGenerator.cs
- Sharpmake/Project.Configuration.cs
Right now, only the folder path of the precompiled header file can be modified. The file name is forced to use the project's name.
This pull request introduces a configuration option to modify the file name. In my case, this allows me to share the precompiled header file between multiple projects. This was not possible before because of the reason mentioned above.
> Add option to change the name of the precompiled header output file

- Sharpmake.Generators/VisualStudio/Csproj.cs
- Sharpmake/Options.CSharp.cs
As of now, Sharpmake is only supporting the "default" debug type options for C# projects. Those are `full` and `pdbonly`. However, there are two more options for generating portable Program Debug Database as described in the Microsoft's documentation: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation
The portable and embedded options are useful for tools that support only the open-source standard: https://github.com/dotnet/core/blob/90ff62b74898499466bb8423d44bedf4b34bf9b0/Documentation/diagnostics/portable_pdb.md
> Portable debug types for C# projects

- .github/workflows/actions.yml
GitHub Actions changes:
- Build jobs artifact name used for MSBuild binary log was conflicting. They were overwritting each others artifact.
- Added MSBuild binary log artifact to samples jobs. Only stored on job failure.
> Fix MSBuild binary logs artifacts of build jobs and add them for samples jobs on GitHub CI

- .github/workflows/actions.yml
- .github/workflows/build.yml
- .github/workflows/release.yml
- Get-Changelog.ps1
Workflow is run only on tags and automate the creation of the GitHub release.
An example of the created release can be for this fake release: https://github.com/sylvainfortin/Sharpmake/releases/tag/0.25.6. This release was the result of this release workflow: https://github.com/sylvainfortin/Sharpmake/actions/runs/4557636578.
EDIT: Also added a fix for the build job to fix a GitVersion issue when the workflow is triggered by a pull request coming from a fork.
> Add GitHub Actions release workflow

- Directory.Build.props
- Sharpmake.UnitTests/SharpmakeFileParserTest.cs
- Sharpmake/AttributeParsers.cs
Hi folks,
It would be quite handy to use environment variables inside the path of module includes, like this:
`
[module:Include(@"%BUILD_TOOLS%\Tool1\SharpMake.Tool1.Project.cs")]
`
Do you think that's a good idea, or would you suggest a better alternative? If you think it's a useful feature, please consider reviewing this pull request.
Each environment variable is quoted with the percent sign character (%), the same behavior specified by `System.Environment.ExpandEnvironmentVariables`. 
Thank you!
Best regards,
Cesar
> Add environment variable expansion to Include attribute

- Sharpmake.Generators/VisualStudio/Csproj.Template.cs
- Sharpmake.Generators/VisualStudio/Csproj.cs
- Sharpmake/Options.CSharp.cs
The following is needed for NativeAOT to be enabled in a .Net 7 app 
This Pull Request adds the required option.
```
<PropertyGroup>
<PublishAot>true</PublishAot>
</PropertyGroup>
```
https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/
> Add PublishAot Option to allow NativeAot on .Net7

- Sharpmake.Platforms/Sharpmake.CommonPlatforms/BasePlatform.Vcxproj.Template.cs
- samples/JumboBuild/reference/projects/jumbobuild_vs2019_win32.vcxproj
- samples/JumboBuild/reference/projects/jumbobuild_vs2019_win64.vcxproj
Move jumbo build configuration parameters to ClCompile block
While enabling the unity build needs to be in the PropertyGroup, the configuration parameters need to be in ClCompile in order to be picked up correctly.
> Fix configuration of MSBuild unity/jumbo build parameters

- Sharpmake.Generators/VisualStudio/Vcxproj.cs
- Sharpmake/Project.Configuration.cs
This mainly adds two flags, `ResolveExecutable` and `DependOnExecutable`.
First one is basically to skip prefixing the `Executable` string with the project path. This allows running of programs that are in the environment but not in the project.
My use case was running a shader compiler while not adding the executable to the project.
The second flag is to skip adding the executable to the list of `AdditionalInputs`, this prevents
a warning when the executable is not found in the project.
The first flag has a workaround by overriding `MakeRelativePaths` but the second flag does not have any workaround I could find.
I'm not extensively familiar with all potential problems that might come up with these flags so any feedback on it would be appreciated.
> Additional Flags for CustomFileBuildStepData

- Sharpmake.Generators/VisualStudio/Vcxproj.Template.cs
- Sharpmake.Generators/VisualStudio/Vcxproj.cs
- Sharpmake/Project.Configuration.cs
This (optionally) allows for specifying to Vcxproj what the output files of a custom build step should be treated as. Useful in contexts where a custom build step generates other build inputs.
I have a use case where we generate C++ wrappers using swig, and want to compile them into the same project that generated them. It's significantly easier to do so if you can provide the OutputItemType field to the build step.
> Added support for OutputItemType to CustomFileBuildStep.

- Sharpmake.Application/Sharpmake.Application.csproj
Fix for samples running on GitHub Mac runners. Latest image contains only .NET 7 and 8 SDKs.
> Add major roll forward to Sharpmake.Application

- .github/workflows/actions.yml
- .github/workflows/build.yml
#320 and #321 needs to be merged in the same PR since they are depending on each other.
This PR will removed all warnings about Node.js 16 in Actions workflows.
> Bump actions/upload-artifact and actions/download-artifact from 3 to 4

- SamplesDef.json
Starting with mac image version 20240722.3, XCodeProjects are crashing during link. To be investigated.
> Temporary XCodeProjects sample removal from GitHub Actions

- Sharpmake.Generators/FastBuild/Bff.Template.cs
- Sharpmake.Generators/VisualStudio/ProjectOptionsGenerator.cs
- Sharpmake.Platforms/Sharpmake.CommonPlatforms/BasePlatform.Vcxproj.Template.cs
- Sharpmake/Options.Vc.cs
Added compiler option "Sharpmake.Options.Vc.Compiler.UseStandardConformingPreprocessor" to set the additional option "/Zc:preprocessor"
https://learn.microsoft.com/en-us/cpp/build/reference/zc-preprocessor?view=msvc-170
> Sharpmake.Options.Vc.Compiler.UseStandardConformingPreprocessor support

- SamplesDef.json
- Sharpmake.UnitTests/Sharpmake.UnitTests.csproj
- samples/PackageReferences/PackageReferences.sharpmake.cs
- samples/PackageReferences/reference/projects/csharppackagereferences/CSharpPackageReferences.vs2019.v4_7_2.csproj
- samples/PackageReferences/reference/projects/csharppackagereferences/CSharpPackageReferences.vs2022.v4_7_2.csproj
- Fix newly reported security vulnerability warnings reported by NuGet.
- Split HelloIOS sample into distinct GitHub and GitLab versions. Allow test execution to fail on GitHub since simulator startup can sometime timeout.
> Fix GitHib Actions build workflow

- Sharpmake.Generators/VisualStudio/Csproj.cs
- Sharpmake/Options.CSharp.cs
- Add support to generated CSharp projects targeting Csharp language version 11, 12 or 13 https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-versioning
> [Minor] Add csharp language versions 11, 12 and 13

- Sharpmake.Platforms/Sharpmake.CommonPlatforms/Android/AndroidAgdePlatform.cs
ClangCompilerTarget is never set when the AndroidAPILevel is set to default, thus causing the Bff scripts to break.
This was the error it throws.
```
...
|| Error: Cannot find path 'ClangCompilerTarget' in parameter path 'cmdLineOptions.ClangCompilerTarget' in '
||     .CompilerExtraOptions   = ''
||             // System options
||             // -------------------------
||             + ' [cmdLineOptions.ClangDiagnosticsFormat]'
||             + ' [cmdLineOptions.ClangCompilerTarget]'
||
...
```
Edit: I'm experimenting with AGDE as I go and I ran into this immediately trying to get FastBuild going. If the `-target` flag is actually required (which I will find out) then this isn't a good fix at all.
> Fixed Bff file error when AndroidAPILevel not set

- SamplesDef.json
- Sharpmake.Generators/VisualStudio/Vcxproj.Template.cs
- Sharpmake.Generators/VisualStudio/Vcxproj.cs
- Sharpmake/Project.cs
- samples/CPPForcePackageReference/CPPForcePackageReference.sharpmake.cs
- samples/CPPForcePackageReference/codebase/Directory.Build.props
- samples/CPPForcePackageReference/codebase/main.cpp
- samples/CPPForcePackageReference/reference/projects/cppforcepackagereference_vs2022_win64.sln
- samples/CPPForcePackageReference/reference/projects/cppforcepackagereference_vs2022_win64.vcxproj
- samples/CPPForcePackageReference/reference/projects/cppforcepackagereference_vs2022_win64.vcxproj.filters
- samples/PackageReferences/reference/projects/cpppackagereferences/cpppackagereferences.vs2019.v4_7_2.vcxproj
- samples/PackageReferences/reference/projects/cpppackagereferences/cpppackagereferences.vs2022.v4_7_2.vcxproj
- samples/Properties/launchSettings.json
Old Behaviour: `/build/native/*.targets` and `/build/*.targets` are both imported.
Problem: in common, `/build/native/*.targets` for C++ project is firstly chosen if presented, old logic will make  `/build/*.targets` also be imported, and in before of `/build/native/*.targets`, causing troubles. 
e.g. Microsoft.WindowsAppSDK
Current Behaviour:  `/build/native/*.targets` import is made before `/build/*.targets` , it will check if `/build/native/*.targets` 
is not presented, then do the `/build/*.targets` import.
---
The current NuGet support for C++ project is incomplete.
- `.props` file import is not supported.
- lack methods to determine if `.targets` and `.props` files are initially presented in order to generate correct error check.
- Irregular path to `.targets` and `.props` files are …
> [Vcxproj] Improve NuGet handling in packages.config mode & add necessary logic for package reference mode
